version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb123123
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  backend_application:
    image: backend22
    container_name: backend_application
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://mongodb123123:27017"

volumes:
  mongodb_data:
